import Head from 'next/head'  
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'
import axios from "axios";

function Dogs({ imglink }) {
  return <>
  <div className={styles.dogContainer}>
    {imglink.map((items, itemIn)=> { 
      return <img key={itemIn} className={styles.dogImage} alt="aaa" src={items} width={200} height={200}/>
    })}
  </div>
    </>
}

export default function Home() {
  const [images, setImages] = useState(null);

  const fetchDog = async () => {
    setImages(null)
    const url = `http://shibe.online/api/shibes?count=10&urls=true&httpsUrls=true`;
    let data = await axios.get(url);
    setImages(data.data)
  };

  useEffect(() => {
    fetchDog()
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.titleScreen}>Koleksi Anjing Shiba</h1>
        { images && <Dogs imglink={images} ></Dogs>}
      </main>
    </>
  )
}
